### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by chenjr0719** [Sanic-Extensions/sanic-mongo#1]
Hi, I want to use pip to install this module, but there is a error happened.

In your setup.py, there is a [typo](https://github.com/Sanic-Extensions/sanic-mongo/blob/master/setup.py#L16) about required module.

The "1motor>=1.1" should be "motor>=1.1"

Please fix this
Thanks

**Comment by hsz1273327** [comment]
thanks~,i will fix it soon.



Regards

HSZ.

Tel: +86 15851390734
E-mail: hsz1273327@gmail.com
github: https://github.com/hsz1273327
website: http://blog.hszofficial.site/
Please consider the environment before printing this email.


2017-04-26 10:31 GMT+08:00 Jacob <notifications@github.com>:

**Comment by chenjr0719** [comment]
Hi, I use pip install from this git alternatively. And the installation is success, but when I use it in my code, it still have error.

The error:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  from sanic_mongo import Mongo
  File "/home/jacob/Python/Part_Time/website/VENV/lib/python3.5/site-packages/sanic_mongo/__init__.py", line 9, in <module>
  from sanic_mongo.mongo import Core as MongoCore
  File "/home/jacob/Python/Part_Time/website/VENV/lib/python3.5/site-packages/sanic_mongo/mongo.py", line 17, in <module>
  from sanic_mongo.standalone import MongoConnection
ImportError: No module named 'sanic_mongo.standalone'
```

This is because of you were missed to add **sanic_mongo.standalone** in [setup.py](https://github.com/Sanic-Extensions/sanic-mongo/blob/master/setup.py#L91).

It should looks like:
```
packages=['sanic_mongo', 'sanic_mongo.standalone'],
```

After this modify, I can import with no error.
But still can't use. :cry: :cry: :cry:
Maybe I will open another issue after some test.

Thanks
